create extension if not exists "pgcrypto";

create schema if not exists analytics;

create table if not exists analytics.import_batches (
  id uuid primary key default gen_random_uuid(),
  report_date date not null,
  source_day_key text not null,
  status text not null default 'pending' check (status in ('pending', 'importing', 'ready', 'failed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_date, source_day_key)
);

create table if not exists analytics.import_files (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  source_type text not null check (source_type in ('faceid', 'aa_ble')),
  report_date date not null,
  google_file_id text,
  file_name text not null,
  mime_type text,
  file_checksum text,
  imported_at timestamptz,
  parse_status text not null default 'pending' check (parse_status in ('pending', 'parsed', 'failed')),
  error_message text,
  raw_storage_path text,
  created_at timestamptz not null default now()
);

create table if not exists analytics.supervisors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.schedules (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.employees (
  id bigint generated by default as identity primary key,
  employee_number text not null unique,
  full_name text not null,
  object_name text,
  customer_tab_number text,
  area_name text,
  profession text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists analytics.shifts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null unique,
  employee_id bigint not null references analytics.employees(id),
  supervisor_id bigint references analytics.supervisors(id),
  schedule_id bigint references analytics.schedules(id),
  planned_start_at timestamptz,
  planned_end_at timestamptz,
  watch_received_at timestamptz,
  watch_returned_at timestamptz,
  on_watch_duration_text text,
  on_watch_duration_seconds integer,
  shift_over_18_hours boolean,
  late_seconds integer,
  early_return_seconds integer,
  calc_hash text,
  created_at timestamptz not null default now()
);

create table if not exists analytics.sessions (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references analytics.shifts(id) on delete cascade,
  tech_session_id bigint not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.ble_minute_facts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  tech_session_id bigint not null,
  employee_number text not null,
  user_id text,
  event_at timestamptz not null,
  object_date date,
  object_time text,
  idle_sec integer not null default 0,
  go_sec integer not null default 0,
  work_sec integer not null default 0,
  total_sec integer not null default 0,
  ble_tags jsonb,
  metka text,
  zona text,
  chosen_metka text,
  chosen_mapped_metka text,
  working_hours numeric,
  work_code text,
  sleep integer,
  wear integer,
  created_at timestamptz not null default now(),
  unique (tech_session_id, event_at)
);

create index if not exists idx_import_files_batch_id on analytics.import_files(batch_id);
create index if not exists idx_shifts_report_date on analytics.shifts(report_date);
create index if not exists idx_shifts_employee_id on analytics.shifts(employee_id);
create index if not exists idx_ble_facts_report_date on analytics.ble_minute_facts(report_date);
create index if not exists idx_ble_facts_shift_id on analytics.ble_minute_facts(ww_shift_id);
create index if not exists idx_ble_facts_session_id on analytics.ble_minute_facts(tech_session_id);
create index if not exists idx_ble_facts_event_at on analytics.ble_minute_facts(event_at);

create or replace view analytics.shift_daily_metrics as
select
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name as supervisor_name,
  sch.name as schedule_name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds,
  count(b.id) as telemetry_rows,
  coalesce(sum(b.idle_sec), 0) as idle_sec_total,
  coalesce(sum(b.go_sec), 0) as go_sec_total,
  coalesce(sum(b.work_sec), 0) as work_sec_total,
  coalesce(sum(b.total_sec), 0) as total_sec_total,
  coalesce(sum(case when b.wear = 1 then b.total_sec else 0 end), 0) as wear_sec_total,
  coalesce(sum(case when b.sleep = 1 then b.total_sec else 0 end), 0) as sleep_sec_total
from analytics.shifts s
join analytics.employees e on e.id = s.employee_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
left join analytics.schedules sch on sch.id = s.schedule_id
left join analytics.ble_minute_facts b on b.ww_shift_id = s.ww_shift_id
group by
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name,
  sch.name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds;

grant usage on schema analytics to anon, authenticated, service_role;

grant select, insert, update, delete on all tables in schema analytics to service_role;
grant select on all tables in schema analytics to authenticated;
grant select on all tables in schema analytics to anon;

grant usage, select on all sequences in schema analytics to service_role;
grant usage, select on all sequences in schema analytics to authenticated;
grant usage, select on all sequences in schema analytics to anon;

alter default privileges in schema analytics
grant select, insert, update, delete on tables to service_role;

alter default privileges in schema analytics
grant select on tables to authenticated;

alter default privileges in schema analytics
grant select on tables to anon;

alter default privileges in schema analytics
grant usage, select on sequences to service_role;

alter default privileges in schema analytics
grant usage, select on sequences to authenticated;

alter default privileges in schema analytics
grant usage, select on sequences to anon;
