create extension if not exists "pgcrypto";

create schema if not exists analytics;

create table if not exists analytics.import_batches (
  id uuid primary key default gen_random_uuid(),
  report_date date not null,
  source_day_key text not null,
  status text not null default 'pending' check (status in ('pending', 'importing', 'ready', 'failed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_date, source_day_key)
);

create table if not exists analytics.import_files (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  source_type text not null check (source_type in ('faceid', 'aa_ble', 'long_idle', 'idle_episode')),
  report_date date not null,
  google_file_id text,
  file_name text not null,
  mime_type text,
  file_checksum text,
  imported_at timestamptz,
  parse_status text not null default 'pending' check (parse_status in ('pending', 'parsed', 'failed')),
  error_message text,
  raw_storage_path text,
  created_at timestamptz not null default now()
);

create table if not exists analytics.supervisors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.schedules (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.employees (
  id bigint generated by default as identity primary key,
  employee_number text not null unique,
  full_name text not null,
  object_name text,
  customer_tab_number text,
  area_name text,
  profession text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists analytics.shifts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null unique,
  employee_id bigint not null references analytics.employees(id),
  supervisor_id bigint references analytics.supervisors(id),
  schedule_id bigint references analytics.schedules(id),
  planned_start_at timestamptz,
  planned_end_at timestamptz,
  watch_received_at timestamptz,
  watch_returned_at timestamptz,
  on_watch_duration_text text,
  on_watch_duration_seconds integer,
  shift_over_18_hours boolean,
  late_seconds integer,
  early_return_seconds integer,
  calc_hash text,
  created_at timestamptz not null default now()
);

create table if not exists analytics.sessions (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references analytics.shifts(id) on delete cascade,
  tech_session_id bigint not null unique,
  created_at timestamptz not null default now()
);

create table if not exists analytics.ble_minute_facts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  tech_session_id bigint not null,
  employee_number text not null,
  user_id text,
  event_at timestamptz not null,
  object_date date,
  object_time text,
  idle_sec integer not null default 0,
  go_sec integer not null default 0,
  work_sec integer not null default 0,
  total_sec integer not null default 0,
  ble_tags jsonb,
  metka text,
  zona text,
  chosen_metka text,
  chosen_mapped_metka text,
  working_hours numeric,
  work_code text,
  sleep integer,
  wear integer,
  created_at timestamptz not null default now(),
  unique (tech_session_id, event_at)
);

create table if not exists analytics.long_idle_facts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  employee_number text,
  customer_tab_number text,
  full_name text,
  area_name text,
  supervisor_name text,
  profession text,
  object_name text,
  shift_begin_at timestamptz,
  shift_end_at timestamptz,
  on_watch_duration_text text,
  schedule_name text,
  eui_device_id text,
  tech_session_id bigint not null,
  full_go numeric,
  real_go numeric,
  full_work numeric,
  real_work numeric,
  full_idle numeric,
  real_idle numeric,
  full_idle_seconds integer not null default 0,
  real_idle_seconds integer not null default 0,
  full_go_seconds integer not null default 0,
  real_go_seconds integer not null default 0,
  full_work_seconds integer not null default 0,
  real_work_seconds integer not null default 0,
  full_total_seconds integer not null default 0,
  real_total_seconds integer not null default 0,
  full_long_idle_seconds integer not null default 0,
  full_common_idle_seconds integer not null default 0,
  long_data_idle_seconds integer not null default 0,
  long_data_total_seconds integer not null default 0,
  real_common_idle numeric,
  real_long_idle numeric,
  created_at timestamptz not null default now(),
  unique (batch_id, ww_shift_id, tech_session_id)
);

create index if not exists idx_import_files_batch_id on analytics.import_files(batch_id);
create index if not exists idx_long_idle_facts_report_date on analytics.long_idle_facts(report_date);
create index if not exists idx_long_idle_facts_shift_id on analytics.long_idle_facts(ww_shift_id);
create index if not exists idx_long_idle_facts_batch_id on analytics.long_idle_facts(batch_id);
create index if not exists idx_shifts_report_date on analytics.shifts(report_date);
create index if not exists idx_shifts_employee_id on analytics.shifts(employee_id);
create index if not exists idx_ble_facts_report_date on analytics.ble_minute_facts(report_date);
create index if not exists idx_ble_facts_shift_id on analytics.ble_minute_facts(ww_shift_id);
create index if not exists idx_ble_facts_session_id on analytics.ble_minute_facts(tech_session_id);
create index if not exists idx_ble_facts_event_at on analytics.ble_minute_facts(event_at);

create or replace function analytics.is_lunch_minute(p_event_at timestamptz)
returns boolean
language sql
stable
security definer
set search_path = analytics, public, pg_temp
as $$
  select (
    (extract(hour from p_event_at at time zone 'Europe/Moscow') * 60
      + extract(minute from p_event_at at time zone 'Europe/Moscow'))::int
      >= coalesce((select kpp_lunch_start_min from analytics.metric_settings where id limit 1), 780)
    and (extract(hour from p_event_at at time zone 'Europe/Moscow') * 60
      + extract(minute from p_event_at at time zone 'Europe/Moscow'))::int
      < coalesce((select kpp_lunch_end_min from analytics.metric_settings where id limit 1), 840)
  );
$$;

create or replace function analytics.is_kpp_metric_minute(p_zona text, p_event_at timestamptz)
returns boolean
language sql
immutable
parallel safe
as $$
  select p_zona = '13'
    and not (
      (p_event_at at time zone 'Europe/Moscow')::time >= time '13:00'
      and (p_event_at at time zone 'Europe/Moscow')::time < time '14:00'
    );
$$;

create or replace function analytics.is_rest_zone(p_zona text)
returns boolean
language sql
immutable
parallel safe
as $$
  select coalesce(p_zona, '') in ('2', '4', '5', '14');
$$;

create or replace function analytics.is_not_worn_eligible_zone(p_zona text)
returns boolean
language sql
immutable
parallel safe
as $$
  select not analytics.is_rest_zone(p_zona)
    and coalesce(trim(p_zona), '') <> '0';
$$;

create or replace function analytics.is_not_worn_metric_minute(
  p_idle_sec integer,
  p_work_sec integer,
  p_go_sec integer,
  p_total_sec integer,
  p_zona text,
  p_profession text,
  p_event_at timestamptz
)
returns boolean
language sql
stable
security definer
set search_path = analytics, public, pg_temp
as $$
  select analytics.is_not_worn_eligible_zone(p_zona)
    and not analytics.is_lunch_minute(p_event_at)
    and coalesce(p_total_sec, 0) > 0
    and coalesce(p_idle_sec, 0) >= analytics.not_worn_idle_sec_min_for(p_profession)
    and coalesce(p_work_sec, 0) + coalesce(p_go_sec, 0) <= analytics.not_worn_active_sec_max_for(p_profession);
$$;

create or replace function analytics.not_worn_episode_minutes_for_date(
  p_report_date date,
  p_shift_ids bigint[] default null
)
returns table (
  ww_shift_id bigint,
  event_at timestamptz,
  total_sec integer
)
language sql
stable
security definer
set search_path = analytics, public, pg_temp
as $$
  with suspicious as (
    select
      b.ww_shift_id,
      b.event_at,
      coalesce(b.total_sec, 60) as total_sec
    from analytics.ble_minute_facts b
    join analytics.shifts s on s.ww_shift_id = b.ww_shift_id and s.report_date = b.report_date
    join analytics.employees e on e.id = s.employee_id
    where b.report_date = p_report_date
      and (p_shift_ids is null or b.ww_shift_id = any(p_shift_ids))
      and analytics.is_not_worn_metric_minute(
        b.idle_sec,
        b.work_sec,
        b.go_sec,
        b.total_sec,
        b.zona,
        e.profession,
        b.event_at
      )
  ),
  marked as (
    select
      ww_shift_id,
      event_at,
      total_sec,
      case
        when lag(event_at) over (partition by ww_shift_id order by event_at) is null
          or event_at - lag(event_at) over (partition by ww_shift_id order by event_at) > interval '90 seconds'
        then 1
        else 0
      end as is_new_episode
    from suspicious
  ),
  grouped as (
    select
      ww_shift_id,
      event_at,
      total_sec,
      sum(is_new_episode) over (partition by ww_shift_id order by event_at) as episode_id
    from marked
  ),
  qualifying as (
    select ww_shift_id, episode_id
    from grouped
    group by ww_shift_id, episode_id
    having sum(total_sec) >= analytics.not_worn_min_interval_sec()
  )
  select g.ww_shift_id, g.event_at, g.total_sec::integer
  from grouped g
  inner join qualifying q using (ww_shift_id, episode_id);
$$;

create or replace function analytics.not_worn_episode_totals_for_date(p_report_date date)
returns table (
  ww_shift_id bigint,
  not_worn_sec_total bigint
)
language sql
stable
security definer
set search_path = analytics, public, pg_temp
as $$
  select
    m.ww_shift_id,
    sum(m.total_sec)::bigint as not_worn_sec_total
  from analytics.not_worn_episode_minutes_for_date(p_report_date, null) m
  group by m.ww_shift_id
  having sum(m.total_sec) > 0;
$$;

create or replace function analytics.list_not_worn_shifts_for_date(p_report_date date)
returns table (
  ww_shift_id bigint,
  employee_number text,
  full_name text,
  profession text,
  supervisor_name text,
  not_worn_sec_total bigint,
  not_worn_eligible_sec_total bigint,
  not_worn_shift_min_sec integer
)
language sql
stable
security definer
set search_path = analytics, public, pg_temp
as $$
  select
    s.ww_shift_id,
    e.employee_number,
    e.full_name,
    e.profession,
    coalesce(sup.name, 'Без начальника') as supervisor_name,
    nw.not_worn_sec_total,
    m.not_worn_eligible_sec_total,
    analytics.not_worn_min_sec_for(e.profession)::integer as not_worn_shift_min_sec
  from analytics.shifts s
  join analytics.employees e on e.id = s.employee_id
  left join analytics.supervisors sup on sup.id = s.supervisor_id
  join analytics.not_worn_episode_totals_for_date(p_report_date) nw on nw.ww_shift_id = s.ww_shift_id
  join analytics.shift_daily_metrics m
    on m.report_date = s.report_date
   and m.ww_shift_id = s.ww_shift_id
  where s.report_date = p_report_date;
$$;

grant execute on function analytics.not_worn_episode_minutes_for_date(date, bigint[]) to anon, authenticated, service_role;
grant execute on function analytics.not_worn_episode_totals_for_date(date) to anon, authenticated, service_role;
grant execute on function analytics.list_not_worn_shifts_for_date(date) to anon, authenticated, service_role;

create or replace view analytics.shift_daily_metrics as
select
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  e.profession,
  sup.name as supervisor_name,
  sch.name as schedule_name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds,
  count(b.id) as telemetry_rows,
  coalesce(sum(b.idle_sec), 0) as idle_sec_total,
  coalesce(max(ep.long_idle_sec_total), 0) as long_idle_sec_total,
  greatest(
    coalesce(sum(b.idle_sec), 0) - coalesce(max(ep.long_idle_sec_total), 0),
    0
  ) as weak_activity_sec_total,
  coalesce(sum(b.go_sec), 0) as go_sec_total,
  coalesce(sum(b.work_sec), 0) as work_sec_total,
  coalesce(sum(b.total_sec), 0) as total_sec_total,
  coalesce(sum(case when b.wear = 1 then b.total_sec else 0 end), 0) as wear_sec_total,
  0::bigint as not_worn_sec_total,
  coalesce(
    sum(
      case
        when analytics.is_not_worn_eligible_zone(b.zona)
          and not analytics.is_lunch_minute(b.event_at)
        then b.total_sec
        else 0
      end
    ),
    0
  ) as not_worn_eligible_sec_total,
  analytics.not_worn_min_sec_for(e.profession) as not_worn_shift_min_sec,
  -- zona=1 is the work zone (ПВ); see docs/zones-reference.md.
  coalesce(sum(case when b.zona = '1' then b.total_sec else 0 end), 0) as pv_sec_total,
  coalesce(sum(case when b.zona is not null and b.zona <> '1' then b.total_sec else 0 end), 0) as outside_pv_sec_total,
  -- КПП: zona=13, кроме обеда 13:00–14:00 (МСК); см. analytics.is_kpp_metric_minute.
  coalesce(
    sum(case when analytics.is_kpp_metric_minute(b.zona, b.event_at) then b.total_sec else 0 end),
    0
  ) as kpp_sec_total
from analytics.shifts s
join analytics.employees e on e.id = s.employee_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
left join analytics.schedules sch on sch.id = s.schedule_id
left join analytics.ble_minute_facts b on b.ww_shift_id = s.ww_shift_id and b.report_date = s.report_date
left join (
  select
    ww_shift_id,
    report_date,
    coalesce(sum(duration_min), 0) * 60 as long_idle_sec_total
  from analytics.idle_episodes
  where duration_min >= 10
  group by ww_shift_id, report_date
) ep on ep.ww_shift_id = s.ww_shift_id and ep.report_date = s.report_date
group by
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  e.profession,
  sup.name,
  sch.name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds;

create or replace view analytics.brigade_daily_metrics as
select
  report_date,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(*) as workers,
  sum(work_sec_total) as work_sec,
  sum(weak_activity_sec_total) as weak_activity_sec,
  sum(long_idle_sec_total) as long_idle_sec,
  sum(go_sec_total) as go_sec,
  sum(total_sec_total) as total_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  sum(not_worn_sec_total) as not_worn_sec,
  sum(not_worn_eligible_sec_total) as not_worn_eligible_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_workers,
  count(*) filter (where not_worn_sec_total >= not_worn_shift_min_sec) as not_worn_workers,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1)
    else 0 end as activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(weak_activity_sec_total) / sum(total_sec_total), 1)
    else 0 end as weak_activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(long_idle_sec_total) / sum(total_sec_total), 1)
    else 0 end as long_idle_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(go_sec_total) / sum(total_sec_total), 1)
    else 0 end as go_pct,
  case when sum(not_worn_eligible_sec_total) > 0
    then round(100.0 * sum(not_worn_sec_total) / sum(not_worn_eligible_sec_total), 1)
    else 0 end as not_worn_pct,
  coalesce(
    round(avg(on_watch_duration_seconds) filter (where on_watch_duration_seconds > 0)),
    0
  )::integer as avg_shift_duration_sec
from analytics.shift_daily_metrics
group by report_date, coalesce(supervisor_name, 'Без начальника');

create or replace view analytics.brigade_weekly_metrics as
select
  (date_trunc('week', report_date))::date as week_start,
  ((date_trunc('week', report_date))::date + 6) as week_end,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(distinct report_date) as days,
  count(distinct employee_number) as unique_employees,
  round(count(*)::numeric / nullif(count(distinct report_date), 0), 1) as avg_workers,
  sum(work_sec_total) as work_sec,
  sum(weak_activity_sec_total) as weak_activity_sec,
  sum(long_idle_sec_total) as long_idle_sec,
  sum(go_sec_total) as go_sec,
  sum(total_sec_total) as total_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_shifts,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1)
    else 0 end as activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(weak_activity_sec_total) / sum(total_sec_total), 1)
    else 0 end as weak_activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(long_idle_sec_total) / sum(total_sec_total), 1)
    else 0 end as long_idle_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(go_sec_total) / sum(total_sec_total), 1)
    else 0 end as go_pct,
  coalesce(
    round(avg(on_watch_duration_seconds) filter (where on_watch_duration_seconds > 0)),
    0
  )::integer as avg_shift_duration_sec
from analytics.shift_daily_metrics
group by 1, 2, 3;

create or replace view analytics.zone_daily_metrics as
select
  b.report_date,
  coalesce(sup.name, 'Без начальника') as supervisor_name,
  b.zona,
  sum(
    case
      when analytics.is_kpp_metric_minute(b.zona, b.event_at) then b.total_sec
      when b.zona = '13' then 0
      else b.total_sec
    end
  ) as sec,
  count(
    distinct case
      when b.zona = '13' and not analytics.is_kpp_metric_minute(b.zona, b.event_at) then null
      else b.ww_shift_id
    end
  ) as shifts
from analytics.ble_minute_facts b
left join analytics.shifts s on s.ww_shift_id = b.ww_shift_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
where b.zona is not null
group by b.report_date, coalesce(sup.name, 'Без начальника'), b.zona;

create table if not exists analytics.idle_episodes (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  session_id bigint,
  employee_number text,
  full_name text,
  dt_start timestamptz,
  dt_end timestamptz,
  duration_min integer not null default 0,
  work_type integer,
  work_code integer,
  ble_tag_number bigint,
  ble_tag_zone integer,
  ble_label text,
  created_at timestamptz not null default now()
);

create index if not exists idx_idle_episodes_report_date on analytics.idle_episodes(report_date);
create index if not exists idx_idle_episodes_shift on analytics.idle_episodes(ww_shift_id);
create index if not exists idx_idle_episodes_zone on analytics.idle_episodes(ble_tag_zone);

create or replace view analytics.idle_episodes_daily as
select
  report_date,
  ww_shift_id,
  session_id,
  employee_number,
  full_name,
  dt_start,
  dt_end,
  duration_min,
  ble_tag_zone
from analytics.idle_episodes
where duration_min >= 10;

create or replace view analytics.kpp_minutes_daily as
select
  report_date,
  ww_shift_id,
  event_at
from analytics.ble_minute_facts
where zona = '13';

create or replace view analytics.not_worn_minutes_daily as
with suspicious as (
  select
    b.report_date,
    b.ww_shift_id,
    b.event_at,
    coalesce(b.total_sec, 60) as total_sec
  from analytics.ble_minute_facts b
  join analytics.shifts s on s.ww_shift_id = b.ww_shift_id and s.report_date = b.report_date
  join analytics.employees e on e.id = s.employee_id
  where analytics.is_not_worn_metric_minute(
    b.idle_sec,
    b.work_sec,
    b.go_sec,
    b.total_sec,
    b.zona,
    e.profession,
    b.event_at
  )
),
marked as (
  select
    report_date,
    ww_shift_id,
    event_at,
    total_sec,
    case
      when lag(event_at) over (partition by report_date, ww_shift_id order by event_at) is null
        or event_at - lag(event_at) over (partition by report_date, ww_shift_id order by event_at) > interval '90 seconds'
      then 1
      else 0
    end as is_new_episode
  from suspicious
),
grouped as (
  select
    report_date,
    ww_shift_id,
    event_at,
    total_sec,
    sum(is_new_episode) over (partition by report_date, ww_shift_id order by event_at) as episode_id
  from marked
),
qualifying as (
  select report_date, ww_shift_id, episode_id
  from grouped
  group by report_date, ww_shift_id, episode_id
  having sum(total_sec) >= analytics.not_worn_min_interval_sec()
)
select g.report_date, g.ww_shift_id, g.event_at, g.total_sec
from grouped g
inner join qualifying q using (report_date, ww_shift_id, episode_id);

create table if not exists analytics.email_recipients (
  id bigint generated by default as identity primary key,
  email text not null,
  label text,
  daily boolean not null default true,
  weekly boolean not null default true,
  active boolean not null default true,
  audience text not null default 'managers' check (audience in ('managers', 'foremen')),
  brigade_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists email_recipients_unique_target
  on analytics.email_recipients (email, audience, coalesce(brigade_name, ''));

alter table analytics.email_recipients
  drop constraint if exists email_recipients_foremen_brigade;

alter table analytics.email_recipients
  add constraint email_recipients_foremen_brigade
  check (audience = 'managers' or brigade_name is not null);

create table if not exists analytics.email_log (
  id bigint generated by default as identity primary key,
  report_type text not null check (report_type in ('daily', 'weekly')),
  period_key text not null,
  recipients text[] not null default '{}',
  status text not null check (status in ('sent', 'failed')),
  audience text not null default 'managers',
  brigade_name text,
  error_message text,
  triggered_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_email_log_created_at on analytics.email_log(created_at desc);

create table if not exists analytics.volume_entries (
  id bigint generated by default as identity primary key,
  report_date date not null,
  label text not null default '',
  value_text text not null,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_volume_entries_report_date
  on analytics.volume_entries (report_date desc, sort_order, id);

create or replace function analytics.touch_volume_entries()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_volume_entries_updated_at on analytics.volume_entries;
create trigger trg_volume_entries_updated_at
before update on analytics.volume_entries
for each row
execute function analytics.touch_volume_entries();

grant select on analytics.volume_entries to anon, authenticated, service_role;
grant select, insert, update, delete on analytics.volume_entries to service_role;

alter table analytics.volume_entries enable row level security;

drop policy if exists volume_entries_public_read on analytics.volume_entries;
create policy volume_entries_public_read
  on analytics.volume_entries
  for select
  to anon, authenticated
  using (true);

grant usage on schema analytics to anon, authenticated, service_role;

grant select, insert, update, delete on all tables in schema analytics to service_role;
grant select on all tables in schema analytics to authenticated;
grant select on all tables in schema analytics to anon;

grant usage, select on all sequences in schema analytics to service_role;
grant usage, select on all sequences in schema analytics to authenticated;
grant usage, select on all sequences in schema analytics to anon;

alter default privileges in schema analytics
grant select, insert, update, delete on tables to service_role;

alter default privileges in schema analytics
grant select on tables to authenticated;

alter default privileges in schema analytics
grant select on tables to anon;

alter default privileges in schema analytics
grant usage, select on sequences to service_role;

alter default privileges in schema analytics
grant usage, select on sequences to authenticated;

alter default privileges in schema analytics
grant usage, select on sequences to anon;

-- Email recipients and log contain PII; keep them server-side only.
revoke select on analytics.email_recipients from anon, authenticated;
revoke select on analytics.email_log from anon, authenticated;
