export const defaultUiText = {
  brand: 'Legenda Analytics',
  heroTitle: 'Здесь умный текст про сравнение',
  heroDescription:
    'Верхний блок теперь ориентирован именно на сравнение бригад. Ниже можно провалиться в людей, отсортировать смены и быстро увидеть, где работа, простой и сон расходятся сильнее всего.',
  compareTitle: 'Сравнение бригад',
  compareEmpty: 'Пока нет данных по бригадам.',
  compareDateFallback: 'Дата не выбрана',
  compareInsights: {
    leader: 'Лидер',
    runnerUp: 'Вторая бригада',
    gap: 'Разница',
    workGap: 'Разница по работе',
    idleGap: 'Разница по простою',
    sleepGap: 'Разница по сну',
    workers: 'Состав',
    tracked: 'Время в часах',
    structure: 'Структура дня',
  },
  filters: {
    date: 'Дата',
    supervisor: 'Руководитель',
    compareMetric: 'Метрика сравнения',
    allBrigades: 'Все бригады',
  },
  compareMetrics: {
    productivity: 'Продуктивность',
    work: 'Рабочее время',
    idle: 'Простой',
    sleep: 'Сон',
  },
  loading: 'Загружаем аналитику из Supabase...',
  noData: 'Нет загруженных отчетных дней.',
  loadErrorPrefix: 'Ошибка загрузки:',
  metrics: {
    workersTitle: 'Сотрудники в выборке',
    workersAllNote: 'Все бригады в выборке',
    workTitle: 'Рабочее время',
    workNote: 'от общего времени',
    idleTitle: 'Время простоя',
    idleNote: 'от общего времени',
    sleepTitle: 'Сон по устройствам',
    sleepNote: 'от общего времени',
  },
  sections: {
    brigadesKicker: 'Бригады',
    brigadesTitle: 'Сравнение по начальникам',
    brigadesDescription:
      'Каждая карточка показывает состав бригады и структуру времени за выбранный день: работа, простой и сон.',
    brigadesLegendTitle: 'Структура времени',
    brigadesBestLabel: 'Лидер по выбранной метрике',
    topKicker: 'Топ 5',
    topTitle: 'Самые продуктивные смены',
    shiftsKicker: 'Смены',
    shiftsTitle: 'Сортируемая таблица за день',
    shiftsHide: 'Скрыть блок',
    shiftsShow: 'Показать блок',
    shiftsHiddenNote: 'Таблица скрыта. Ее можно вернуть одной кнопкой.',
  },
  table: {
    worker: 'Сотрудник',
    supervisor: 'Начальник',
    work: 'Работа',
    idle: 'Простой',
    total: 'Всего',
    productivity: 'Продуктивность',
    sleep: 'Сон',
    noSupervisor: 'Без начальника',
  },
  compareMeta: {
    workersSuffix: 'сотрудников',
    inReportSuffix: 'в отчете',
    trackedSuffix: 'время в часах',
  },
  editor: {
    open: 'Редактировать тексты',
    close: 'Закрыть редактор',
    title: 'Редактор текстов',
    description:
      'Меняй тексты прямо на странице, сохраняй черновик локально и применяй изменения обратно в uiText.ts.',
    reset: 'Сбросить',
    saveJson: 'Сохранить JSON',
    import: 'Загрузить JSON',
    applyToFile: 'Применить текущие правки в uiText.ts',
    applySuccess: 'Правки записаны в uiText.ts',
    applyErrorPrefix: 'Не удалось записать в uiText.ts:',
    saved: 'Черновик сохранен локально',
  },
  editorFields: {
    brand: 'Бренд',
    heroTitle: 'Главный заголовок',
    heroDescription: 'Описание',
    compareTitle: 'Заголовок сравнения',
    compareEmpty: 'Пустое состояние сравнения',
    filtersDate: 'Дата',
    filtersSupervisor: 'Руководитель',
    filtersCompareMetric: 'Метрика сравнения',
    filtersAllBrigades: 'Все бригады',
    brigadesTitle: 'Заголовок блока бригад',
    shiftsTitle: 'Заголовок блока таблицы',
  },
} as const

export type UiText = typeof defaultUiText
