-- Ручной ввод объёмов за день (дашборд, блок «Объёмы»).
create table if not exists analytics.volume_entries (
  id bigint generated by default as identity primary key,
  report_date date not null,
  label text not null default '',
  value_text text not null,
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_volume_entries_report_date
  on analytics.volume_entries (report_date desc, sort_order, id);

create or replace function analytics.touch_volume_entries()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_volume_entries_updated_at on analytics.volume_entries;
create trigger trg_volume_entries_updated_at
before update on analytics.volume_entries
for each row
execute function analytics.touch_volume_entries();

grant select on analytics.volume_entries to anon, authenticated, service_role;
grant select, insert, update, delete on analytics.volume_entries to service_role;
