-- Dashboard rework + email reports
-- 1. Add КПП (zona 13) to per-shift metrics
-- 2. Brigade daily/weekly aggregate views
-- 3. Email recipients + email log tables

create or replace view analytics.shift_daily_metrics as
select
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name as supervisor_name,
  sch.name as schedule_name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds,
  count(b.id) as telemetry_rows,
  coalesce(sum(b.idle_sec), 0) as idle_sec_total,
  coalesce(sum(b.go_sec), 0) as go_sec_total,
  coalesce(sum(b.work_sec), 0) as work_sec_total,
  coalesce(sum(b.total_sec), 0) as total_sec_total,
  coalesce(sum(case when b.wear = 1 then b.total_sec else 0 end), 0) as wear_sec_total,
  coalesce(sum(case when b.sleep = 1 then b.total_sec else 0 end), 0) as sleep_sec_total,
  -- ponytail: zona=1 is inferred as PV (рабочая зона) from current data; replace with a zone dictionary when available.
  coalesce(sum(case when b.zona = '1' then b.total_sec else 0 end), 0) as pv_sec_total,
  coalesce(sum(case when b.zona is not null and b.zona <> '1' then b.total_sec else 0 end), 0) as outside_pv_sec_total,
  -- КПП: zona=13 is the checkpoint zone.
  coalesce(sum(case when b.zona = '13' then b.total_sec else 0 end), 0) as kpp_sec_total
from analytics.shifts s
join analytics.employees e on e.id = s.employee_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
left join analytics.schedules sch on sch.id = s.schedule_id
left join analytics.ble_minute_facts b on b.ww_shift_id = s.ww_shift_id
group by
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name,
  sch.name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds;

-- Per-brigade metrics for one report day
create or replace view analytics.brigade_daily_metrics as
select
  report_date,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(*) as workers,
  sum(work_sec_total) as work_sec,
  sum(idle_sec_total) as idle_sec,
  sum(total_sec_total) as total_sec,
  sum(sleep_sec_total) as sleep_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_workers,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1)
    else 0 end as activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(idle_sec_total) / sum(total_sec_total), 1)
    else 0 end as idle_pct
from analytics.shift_daily_metrics
group by report_date, coalesce(supervisor_name, 'Без начальника');

-- Per-brigade metrics aggregated by ISO week (Monday start)
create or replace view analytics.brigade_weekly_metrics as
select
  (date_trunc('week', report_date))::date as week_start,
  ((date_trunc('week', report_date))::date + 6) as week_end,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(distinct report_date) as days,
  count(distinct employee_number) as unique_employees,
  round(count(*)::numeric / nullif(count(distinct report_date), 0), 1) as avg_workers,
  sum(work_sec_total) as work_sec,
  sum(idle_sec_total) as idle_sec,
  sum(total_sec_total) as total_sec,
  sum(sleep_sec_total) as sleep_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_shifts,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1)
    else 0 end as activity_pct,
  case when sum(total_sec_total) > 0
    then round(100.0 * sum(idle_sec_total) / sum(total_sec_total), 1)
    else 0 end as idle_pct
from analytics.shift_daily_metrics
group by 1, 2, 3;

-- Email recipients registry
create table if not exists analytics.email_recipients (
  id bigint generated by default as identity primary key,
  email text not null unique,
  label text,
  daily boolean not null default true,
  weekly boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Email send log
create table if not exists analytics.email_log (
  id bigint generated by default as identity primary key,
  report_type text not null check (report_type in ('daily', 'weekly')),
  period_key text not null,
  recipients text[] not null default '{}',
  status text not null check (status in ('sent', 'failed')),
  error_message text,
  triggered_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_email_log_created_at on analytics.email_log(created_at desc);

-- Aggregate views are safe to expose (names + aggregates, same sensitivity as shift_daily_metrics)
grant select on analytics.brigade_daily_metrics to anon, authenticated, service_role;
grant select on analytics.brigade_weekly_metrics to anon, authenticated, service_role;

-- Recipients and log stay server-side only (managed through the send-report edge function)
grant select, insert, update, delete on analytics.email_recipients to service_role;
grant select, insert, update, delete on analytics.email_log to service_role;
grant usage, select on all sequences in schema analytics to service_role;

-- Ensure PII tables are not exposed to public roles even if broad grants ran before.
revoke select on analytics.email_recipients from anon, authenticated;
revoke select on analytics.email_log from anon, authenticated;
