-- Zones + Report 10 (idle episodes) + remove unused sleep metric
--
-- 1. Recreate metric views without sleep_sec (sleep is unused per Workwatch spec).
-- 2. Add zone_daily_metrics view (time per zona per brigade per day).
-- 3. Add idle_episodes table (Report 10 detail) and 'idle_episode' source type.

drop view if exists analytics.brigade_weekly_metrics;
drop view if exists analytics.brigade_daily_metrics;
drop view if exists analytics.shift_daily_metrics;

create view analytics.shift_daily_metrics as
select
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name as supervisor_name,
  sch.name as schedule_name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds,
  count(b.id) as telemetry_rows,
  coalesce(sum(b.idle_sec), 0) as idle_sec_total,
  coalesce(sum(b.go_sec), 0) as go_sec_total,
  coalesce(sum(b.work_sec), 0) as work_sec_total,
  coalesce(sum(b.total_sec), 0) as total_sec_total,
  coalesce(sum(case when b.zona = '1' then b.total_sec else 0 end), 0) as pv_sec_total,
  coalesce(sum(case when b.zona is not null and b.zona <> '1' then b.total_sec else 0 end), 0) as outside_pv_sec_total,
  coalesce(sum(case when b.zona = '13' then b.total_sec else 0 end), 0) as kpp_sec_total
from analytics.shifts s
join analytics.employees e on e.id = s.employee_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
left join analytics.schedules sch on sch.id = s.schedule_id
left join analytics.ble_minute_facts b on b.ww_shift_id = s.ww_shift_id
group by
  s.report_date,
  s.ww_shift_id,
  e.employee_number,
  e.full_name,
  sup.name,
  sch.name,
  s.on_watch_duration_seconds,
  s.late_seconds,
  s.early_return_seconds;

create view analytics.brigade_daily_metrics as
select
  report_date,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(*) as workers,
  sum(work_sec_total) as work_sec,
  sum(idle_sec_total) as idle_sec,
  sum(go_sec_total) as go_sec,
  sum(total_sec_total) as total_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_workers,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1) else 0 end as activity_pct,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(idle_sec_total) / sum(total_sec_total), 1) else 0 end as idle_pct,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(go_sec_total) / sum(total_sec_total), 1) else 0 end as go_pct
from analytics.shift_daily_metrics
group by report_date, coalesce(supervisor_name, 'Без начальника');

create view analytics.brigade_weekly_metrics as
select
  (date_trunc('week', report_date))::date as week_start,
  ((date_trunc('week', report_date))::date + 6) as week_end,
  coalesce(supervisor_name, 'Без начальника') as supervisor_name,
  count(distinct report_date) as days,
  count(distinct employee_number) as unique_employees,
  round(count(*)::numeric / nullif(count(distinct report_date), 0), 1) as avg_workers,
  sum(work_sec_total) as work_sec,
  sum(idle_sec_total) as idle_sec,
  sum(go_sec_total) as go_sec,
  sum(total_sec_total) as total_sec,
  sum(pv_sec_total) as pv_sec,
  sum(kpp_sec_total) as kpp_sec,
  count(*) filter (where kpp_sec_total > 0) as kpp_shifts,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(work_sec_total) / sum(total_sec_total), 1) else 0 end as activity_pct,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(idle_sec_total) / sum(total_sec_total), 1) else 0 end as idle_pct,
  case when sum(total_sec_total) > 0 then round(100.0 * sum(go_sec_total) / sum(total_sec_total), 1) else 0 end as go_pct
from analytics.shift_daily_metrics
group by 1, 2, 3;

-- Time spent per zone per brigade per day (zone dictionary decoded on the frontend).
create view analytics.zone_daily_metrics as
select
  b.report_date,
  coalesce(sup.name, 'Без начальника') as supervisor_name,
  b.zona,
  sum(b.total_sec) as sec,
  count(distinct b.ww_shift_id) as shifts
from analytics.ble_minute_facts b
left join analytics.shifts s on s.ww_shift_id = b.ww_shift_id
left join analytics.supervisors sup on sup.id = s.supervisor_id
where b.zona is not null
group by b.report_date, coalesce(sup.name, 'Без начальника'), b.zona;

-- Report 10: individual long-idle episodes.
alter table analytics.import_files drop constraint if exists import_files_source_type_check;
alter table analytics.import_files
  add constraint import_files_source_type_check
  check (source_type in ('faceid', 'aa_ble', 'long_idle', 'idle_episode'));

create table if not exists analytics.idle_episodes (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  session_id bigint,
  employee_number text,
  full_name text,
  dt_start timestamptz,
  dt_end timestamptz,
  duration_min integer not null default 0,
  work_type integer,
  work_code integer,
  ble_tag_number bigint,
  ble_tag_zone integer,
  ble_label text,
  created_at timestamptz not null default now()
);

create index if not exists idx_idle_episodes_report_date on analytics.idle_episodes(report_date);
create index if not exists idx_idle_episodes_shift on analytics.idle_episodes(ww_shift_id);
create index if not exists idx_idle_episodes_zone on analytics.idle_episodes(ble_tag_zone);

grant select on analytics.brigade_daily_metrics to anon, authenticated, service_role;
grant select on analytics.brigade_weekly_metrics to anon, authenticated, service_role;
grant select on analytics.shift_daily_metrics to anon, authenticated, service_role;
grant select on analytics.zone_daily_metrics to anon, authenticated, service_role;
grant select, insert, update, delete on analytics.idle_episodes to service_role;
grant select on analytics.idle_episodes to anon, authenticated;
grant usage, select on all sequences in schema analytics to service_role;
