-- LongIDLE report source and facts table

alter table analytics.import_files
  drop constraint if exists import_files_source_type_check;

alter table analytics.import_files
  add constraint import_files_source_type_check
  check (source_type in ('faceid', 'aa_ble', 'long_idle'));

create table if not exists analytics.long_idle_facts (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references analytics.import_batches(id) on delete cascade,
  report_date date not null,
  ww_shift_id bigint not null,
  employee_number text,
  customer_tab_number text,
  full_name text,
  area_name text,
  supervisor_name text,
  profession text,
  object_name text,
  shift_begin_at timestamptz,
  shift_end_at timestamptz,
  on_watch_duration_text text,
  schedule_name text,
  eui_device_id text,
  tech_session_id bigint not null,
  full_go numeric,
  real_go numeric,
  full_work numeric,
  real_work numeric,
  full_idle numeric,
  real_idle numeric,
  full_idle_seconds integer not null default 0,
  real_idle_seconds integer not null default 0,
  full_go_seconds integer not null default 0,
  real_go_seconds integer not null default 0,
  full_work_seconds integer not null default 0,
  real_work_seconds integer not null default 0,
  full_total_seconds integer not null default 0,
  real_total_seconds integer not null default 0,
  full_long_idle_seconds integer not null default 0,
  full_common_idle_seconds integer not null default 0,
  long_data_idle_seconds integer not null default 0,
  long_data_total_seconds integer not null default 0,
  real_common_idle numeric,
  real_long_idle numeric,
  created_at timestamptz not null default now(),
  unique (batch_id, ww_shift_id, tech_session_id)
);

create index if not exists idx_long_idle_facts_report_date on analytics.long_idle_facts(report_date);
create index if not exists idx_long_idle_facts_shift_id on analytics.long_idle_facts(ww_shift_id);
create index if not exists idx_long_idle_facts_batch_id on analytics.long_idle_facts(batch_id);

grant select, insert, update, delete on analytics.long_idle_facts to service_role;
grant select on analytics.long_idle_facts to authenticated;
grant select on analytics.long_idle_facts to anon;
